# Define the original sequence
original <- "AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGCTTCTGAACTGGTTACCTGCCGTGAGTAAATTAAAATTTTATTGACTTAGGTCACTAAATACTTTAACCAATATAGGCATAGCGCACAGACAGATAAAAATTACAGAGTACACAACATCCATGAAACGCATTAGCACCACCATTACCACCACCATCACCATTACCACAGGTAACGGTGCGGGCTGACGCGTACAGGAAACACAGAAAAAAGCCCGCACCTGACAGTGCGGGCTTTTTTTTTCGACCAAAGGTAACGAGGTAACAACCATGCGAGTGTTGAAGTTCGGCGGTACATCAGTGGCAAATGCAGAACGTTTTCTGCGTGTTGCCGATATTCTGGAAAGCAATGCCAGGCAGGGGCAGGTGGCCACCGTCCTCTCTGCCCCCGCCAAAATCACCAACCACCTGGTGGCGATGATTGAAAAAACCATTAGCGGCCAGGATGCTTTACCCAATATCAGCGATGCCGAACGTATTTTTGCCGAACTTTTGACGGGACTCGCCGCCGCCCAGCCGGGGTTCCCGCTGGCGCAATTGAAAACTTTCGTCGATCAGGAATTTGCCCAAATAAAACATGTCCTGCATGGCATTAGTTTGTTGGGGCAGTGCCCGGATAGCATCAACGCTGCGCTGATTTGCCGTGGCGAGAAAATGTCGATCGCCATTATGGCCGGCGTATTAGAAGCGCGCGGTCACAACGT$"

# Define the pattern to search for
pattern <- "AGACA"

# Use grep() to find the index of the first match
match_index <- grep(pattern, original)

# Use gregexpr() to find all matches and their positions
matches <- gregexpr(pattern, original)

# Print the first match index
if(length(match_index) > 0){
  cat("The pattern ", pattern, " was found at index ", match_index[1], ".\n")
} else {
  cat("The pattern ", pattern, " was not found in the original sequence.\n")
}

# Print the positions of all matches
if(length(matches[[1]]) > 0){
  cat("The pattern ", pattern, " was found at positions: ", paste(matches[[1]], collapse=" "), ".\n")
} else {
  cat("The pattern ", pattern, " was not found in the original sequence.\n")
}